-- CreateTable
CREATE TABLE "public"."trades" (
    "e" TEXT NOT NULL,
    "E" TIMESTAMP(3) NOT NULL,
    "s" TEXT NOT NULL,
    "a" BIGINT NOT NULL,
    "p" DECIMAL(38,18) NOT NULL,
    "q" DECIMAL(38,18) NOT NULL,
    "f" BIGINT NOT NULL,
    "l" BIGINT NOT NULL,
    "T" TIMESTAMP(3) NOT NULL,
    "m" BOOLEAN NOT NULL,
    "M" BOOLEAN NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "trades_pkey" PRIMARY KEY ("s","T")
);
